name: quizi
description: "Quizi - A Silent Classroom Quiz System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5

  # State management & utilities
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.14
  intl: ^0.18.1

  # UI / UX
  google_fonts: ^6.3.3
  percent_indicator: ^4.2.5

  # Networking & storage
  path_provider: ^2.1.5
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
