// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdxXgYImpqMoGtv80dXdVyh8j86Qh8JXY',
    appId: '1:926031654544:web:79b51a8e9a886cad08b215',
    messagingSenderId: '926031654544',
    projectId: 'quizi-d9753',
    authDomain: 'quizi-d9753.firebaseapp.com',
    storageBucket: 'quizi-d9753.firebasestorage.app',
    measurementId: 'G-K7NSLE85MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK7AtfPAbKuIkESjsrLe-lhPJdqEV4Ndc',
    appId: '1:926031654544:android:cf0a9235b73be66e08b215',
    messagingSenderId: '926031654544',
    projectId: 'quizi-d9753',
    storageBucket: 'quizi-d9753.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY7SrxsAp6i5OYxqu59yti8v95XGRzh2I',
    appId: '1:926031654544:ios:e581d77bc3ce756508b215',
    messagingSenderId: '926031654544',
    projectId: 'quizi-d9753',
    storageBucket: 'quizi-d9753.firebasestorage.app',
    iosBundleId: 'com.example.quizi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY7SrxsAp6i5OYxqu59yti8v95XGRzh2I',
    appId: '1:926031654544:ios:e581d77bc3ce756508b215',
    messagingSenderId: '926031654544',
    projectId: 'quizi-d9753',
    storageBucket: 'quizi-d9753.firebasestorage.app',
    iosBundleId: 'com.example.quizi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdxXgYImpqMoGtv80dXdVyh8j86Qh8JXY',
    appId: '1:926031654544:web:19be4150c993e8a408b215',
    messagingSenderId: '926031654544',
    projectId: 'quizi-d9753',
    authDomain: 'quizi-d9753.firebaseapp.com',
    storageBucket: 'quizi-d9753.firebasestorage.app',
    measurementId: 'G-TLWX2E4TGB',
  );
}
